[keyboard]
name = "lily58 RE"
product_name = "lily58_rp2040"
vendor_id = 0x8D1D
product_id = 0xB4C2 
manufacturer = "hitsmaxft"
chip = "rp2040"
# board = "nice!nano_v2"
usb_enable = true

# [matrix]
# Input and output pins are mandatory
# input_pins = ["PIN_5", "PIN_6", "PIN_7", "PIN_8", "PIN_9"]
# output_pins = ["GP27", "GP26", "GP22", "GP20", "GP23", "GP21"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# default use col2row
# row2col = false

[layout]
rows = 10
cols = 6
layers = 1
keymap = [
    # LBASE layer
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
        ["Tab", "Q", "W", "E", "R", "T"],
        ["LCtrl", "MT(A, LCtrl)", "MT(S,LAlt)", "MT(D,LGui)", "MT(F, LShift)", "G"],
        ["LShift", "Z", "X", "C", "V", "B"],
        ["__", "Kc3", "Kc4", "MO(2)", "LT(3, Space)", "__"],

        ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backspace"],
        ["Y", "U", "I", "O", "P", "Backslash"],
        ["H", "MT(J,RShift)", "MT(K,RGui)", "MT(L, RAlt)", "MT(Semicolon, RCtrl)", "Quote"],
        ["N", "M", "Comma", "Dot", "Slash", "MT(Grave, RShift)"],
        ["__", "Enter", "MO(1)", "LeftBracket", "RightBracket", "__"],
    ],
    
    # LRAISE layer (Layer 1)
    # [
    #     ["Grave", "WM(Kc1, LShift)", "WM(Kc2, LShift)", "WM(Kc3, LShift)", "WM(Kc4, LShift)", "WM(Kc5, LShift)"],
    #     ["_", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5"],
    #     ["_", "F1", "F2", "F3", "F4", "F5"],
    #     ["_", "F7", "F8", "F9", "F10", "F12"],
    #     ["__", "_", "_", "_", "_", "__"],
    #     ["WM(Kc6, LShift)", "WM(Kc7, LShift)", "Minus", "WM(Equal, LShift)", "_", "Backspace"],
    #     ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "WM(Backslash, LShift)"],
    #     ["F6", "Minus", "Equal", "LeftBracket", "RightBracket", "_"],
    #     ["LeftBracket", "RightBracket", "WM(Comma, LShift)", "WM(Dot, LShift)", "WM(Slash, LShift)", "WM(Grave, RShift)"],
    #     ["__", "_", "_", "_", "_", "__"],
    # ],
    
    # # LLOWER layer (Layer 2)
    # [
    #     ["Grave", "WM(Kc1, LShift)", "WM(Kc2, LShift)", "WM(Kc3, LShift)", "WM(Kc4, LShift)", "WM(Kc5, LShift)"],
    #     ["MO(3)", "WM(Kc1, LShift)", "WM(Kc2, LShift)", "WM(Kc3, LShift)", "WM(Kc4, LShift)", "WM(Kc5, LShift)"],
    #     ["_", "F1", "F2", "F3", "F4", "F5"],
    #     ["_", "F7", "F8", "F9", "Tab", "F6"],
    #     ["__", "_", "_", "_", "_", "__"],
    #     ["WM(Kc6, LShift)", "WM(Kc7, LShift)", "Minus", "WM(Equal, LShift)", "_", "Backspace"],
    #     ["WM(Kc6, LShift)", "WM(Kc7, LShift)", "WM(Kc8, LShift)", "WM(Kc9, LShift)", "WM(Kc0, LShift)", "WM(Backslash, LShift)"],
    #     ["Backspace", "KpMinus", "KpEqual", "WM(LeftBracket, LShift)", "WM(RightBracket, LShift)", "Enter"],
    #     ["WM(LeftBracket, LShift)", "WM(RightBracket, LShift)", "Comma", "Dot", "Slash", "Grave"],
    #     ["__", "_", "_", "_", "_", "__"],
    # ],
    
    # # LFUNC layer (Layer 3)
    # [
    #     ["_", "F1", "F2", "F3", "F4", "F5"],
    #     ["MO(4)", "_", "_", "MouseUp", "PageUp", "PageDown"],
    #     ["_", "_", "MouseLeft", "MouseDown", "MouseRight", "F6"],
    #     ["_", "_", "_", "_", "Home", "End"],
    #     ["__", "_", "_", "_", "_", "__"],

    #     ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Grave"],
    #     ["_", "MouseWheelUp", "MouseWheelDown", "_", "P", "Minus"],
    #     ["Left", "Down", "UP", "Right", "Semicolon", "Quote"],
    #     ["MouseBtn1", "MouseBtn2", "Comma", "Dot", "Slash", "RShift"],
    #     ["__", "_", "_", "_", "_", "__"],
    # ],
    
    # # LDEBUG layer (Layer 4)
    # [
    #     ["F", "F1", "F2", "F3", "F4", "F5"],
    #     ["_", "_", "_", "MouseUp", "R", "T"],
    #     ["_", "MouseLeft", "MouseLeft", "DebugToggle", "MouseRight", "F6"],
    #     ["_", "Z", "X", "C", "Home", "Bootloader"],
    #     ["__", "_", "_", "_", "_", "_"],

    #     ["Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Grave"],
    #     ["Y", "U", "I", "O", "P", "Minus"],
    #     ["Left", "Down", "UP", "Down", "Semicolon", "Quote"],
    #     ["N", "M", "Comma", "Dot", "Slash", "RShift"],
    #     ["_", "_", "_", "_", "_", "_"]
    # ]
]


[storage]

[split]
connection = "serial"

# input_pins = ["PIN_5", "PIN_6", "PIN_7", "PIN_8", "PIN_9"]
# output_pins = ["GP27", "GP26", "GP22", "GP20", "GP23", "GP21"]
[split.central]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
serial = [
    { instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" },
]

[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_5", "PIN_6", "PIN_7", "PIN_8", "PIN_9"]
output_pins = ["PIN_27", "PIN_26", "PIN_22", "PIN_20", "PIN_23", "PIN_21"]

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 6
col_offset = 6
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]

[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_5", "PIN_6", "PIN_7", "PIN_8", "PIN_9"]
# output_pins = ["PIN_21", "PIN_23", "PIN_20", "PIN_22", "PIN_26", "PIN_27"]
output_pins = ["PIN_27", "PIN_26", "PIN_22", "PIN_20", "PIN_23", "PIN_21"]

[behavior]

# tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms"}
